#!/usr/bin/env python3
"""
build.py — Framework Registry Build Script

Reads frameworks/*.md and frameworks/_registry.yaml, then patches
practice.html by replacing content between sentinel markers:
  - FRAMEWORK_REGISTRY:FACTOR_TREE_DATA
  - FRAMEWORK_REGISTRY:COACHING_FRAMEWORKS

Usage: python build.py
"""
import sys, io, os, re, json

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PRACTICE_HTML = os.path.join(BASE_DIR, 'practice.html')
API_CONTENT_JS = os.path.join(BASE_DIR, 'functions', 'api', 'practice-content.js')
FRAMEWORKS_DIR = os.path.join(BASE_DIR, 'frameworks')
REGISTRY_FILE = os.path.join(FRAMEWORKS_DIR, '_registry.yaml')

# ── Minimal YAML parser (no dependency needed) ──
# We use a simple approach: parse _registry.yaml for diagram data
# and framework .md files for coaching content via frontmatter

try:
    import yaml
except ImportError:
    yaml = None


def parse_yaml_simple(filepath):
    """Parse YAML file. Uses PyYAML if available, otherwise falls back to json-based approach."""
    if yaml:
        with open(filepath, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)
    else:
        # Fallback: use a subprocess to convert YAML to JSON via Python
        # Since we can't guarantee PyYAML, we'll parse the registry manually
        raise ImportError("PyYAML is required. Install with: pip install pyyaml")


def parse_framework_frontmatter(filepath):
    """Extract YAML frontmatter from a framework .md file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    if not content.startswith('---'):
        return {}

    end = content.index('---', 3)
    frontmatter_text = content[3:end].strip()

    if yaml:
        return yaml.safe_load(frontmatter_text)
    else:
        raise ImportError("PyYAML is required. Install with: pip install pyyaml")


def replace_between_markers(content, marker_name, replacement):
    """Replace content between /* FRAMEWORK_REGISTRY:{name}:START */ and /* FRAMEWORK_REGISTRY:{name}:END */ markers."""
    start_marker = f'/* FRAMEWORK_REGISTRY:{marker_name}:START */'
    end_marker = f'/* FRAMEWORK_REGISTRY:{marker_name}:END */'

    start_idx = content.find(start_marker)
    end_idx = content.find(end_marker)

    if start_idx == -1 or end_idx == -1:
        print(f"  WARN: Could not find markers for {marker_name}")
        return content

    # Replace everything between (and including) the markers
    new_content = content[:start_idx] + start_marker + '\n' + replacement + '\n' + end_marker + content[end_idx + len(end_marker):]
    return new_content


def generate_factor_tree_data(registry):
    """Generate the FACTOR_TREE_DATA JavaScript object from registry diagram data."""
    cases = registry.get('cases', {})
    entries = []

    for case_id, case_data in cases.items():
        diagram = case_data.get('diagram')
        if not diagram:
            continue

        title = diagram.get('title', case_id)
        external = diagram.get('external', [])
        internal = diagram.get('internal', [])

        # Build JS object literal
        ext_parts = []
        for cat in external:
            items_str = ', '.join(f"'{item}'" for item in cat.get('items', []))
            ext_parts.append(f"      {{ name: '{cat['name']}', items: [{items_str}] }}")

        int_parts = []
        for cat in internal:
            items_str = ', '.join(f"'{item}'" for item in cat.get('items', []))
            int_parts.append(f"      {{ name: '{cat['name']}', items: [{items_str}] }}")

        # Escape special chars in title — use JS unicode escapes for arrows
        safe_title = title.replace("'", "\\'").replace('\u2192', '\\u2192')

        ext_block = ',\n'.join(ext_parts)
        int_block = ',\n'.join(int_parts)

        entry = f"  '{case_id}': {{\n    title: '{safe_title}',\n    external: [\n{ext_block}\n    ],\n    internal: [\n{int_block}\n    ]\n  }}"
        entries.append(entry)

    js = "// Factor Tree diagram data — generated by build.py from frameworks/_registry.yaml\n"
    js += "var FACTOR_TREE_DATA = {\n"
    js += ",\n".join(entries)
    js += "\n};\n"

    return js



def generate_coaching_frameworks(frameworks_dir):
    """Generate the SYSTEM_PROMPT coaching frameworks section from framework .md files."""
    framework_files = sorted([
        f for f in os.listdir(frameworks_dir)
        if f.endswith('.md') and not f.startswith('_')
    ])

    sections = []
    sections.append("═══════════════════════════════")
    sections.append("CASE STUDY FRAMEWORKS")
    sections.append("═══════════════════════════════")
    sections.append("Identify the case study type from the user's prompt and follow the matching framework below. Always coach the user through these frameworks step-by-step — don't dump the whole framework at once. Guide them to discover each branch.")

    for i, filename in enumerate(framework_files, 1):
        filepath = os.path.join(frameworks_dir, filename)
        fm = parse_framework_frontmatter(filepath)

        if not fm or 'coaching' not in fm:
            continue

        coaching = fm['coaching']
        name = fm.get('name', filename.replace('.md', ''))
        use_for = coaching.get('use_for', '')
        steps = coaching.get('steps', [])
        style_notes = coaching.get('style_notes', '')

        sections.append("")
        sections.append("──────────────────────────────")
        sections.append(f"FRAMEWORK {i}: {name.upper()}")
        sections.append("──────────────────────────────")
        sections.append(f"Use for: {use_for}")

        for j, step in enumerate(steps, 1):
            title = step.get('title', f'Step {j}')
            prompt = step.get('prompt', '').rstrip()
            sections.append(f"\nStep {j} — {title}")
            # Indent multi-line prompts
            for line in prompt.split('\n'):
                sections.append(line.rstrip())

        if style_notes:
            sections.append(f"\nCOACHING STYLE FOR {name.upper().split('/')[0].strip()}:")
            for line in style_notes.strip().split('\n'):
                sections.append(line.rstrip())

    sections.append("")

    return '\n'.join(sections)


def main():
    print("build.py — Framework Registry Build")
    print("=" * 40)

    # Check PyYAML
    if yaml is None:
        print("ERROR: PyYAML is required. Install with: pip install pyyaml")
        sys.exit(1)

    # Read both target files
    with open(PRACTICE_HTML, 'r', encoding='utf-8') as f:
        html_content = f.read()
    with open(API_CONTENT_JS, 'r', encoding='utf-8') as f:
        api_content = f.read()

    # 1. Load registry
    print("\n1. Loading registry...")
    registry = parse_yaml_simple(REGISTRY_FILE)
    cases_with_diagrams = sum(1 for c in registry.get('cases', {}).values() if c.get('diagram'))
    print(f"   {len(registry.get('cases', {}))} cases mapped, {cases_with_diagrams} with diagram data")

    # 2. Generate and inject FACTOR_TREE_DATA into functions/api/practice-content.js
    print("\n2. Generating FACTOR_TREE_DATA...")
    factor_tree_js = generate_factor_tree_data(registry)
    api_content = replace_between_markers(api_content, 'FACTOR_TREE_DATA', factor_tree_js)
    print(f"   OK: Generated {cases_with_diagrams} factor tree entries -> practice-content.js")

    # 3. Generate and inject COACHING_FRAMEWORKS into practice.html
    print("\n3. Generating COACHING_FRAMEWORKS...")
    coaching_text = generate_coaching_frameworks(FRAMEWORKS_DIR)
    html_content = replace_between_markers(html_content, 'COACHING_FRAMEWORKS', coaching_text)
    framework_count = coaching_text.count('FRAMEWORK ')
    print(f"   OK: Generated {framework_count} coaching frameworks -> practice.html")

    # 4. Write updated files
    with open(API_CONTENT_JS, 'w', encoding='utf-8') as f:
        f.write(api_content)
    with open(PRACTICE_HTML, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f"\n{'=' * 40}")
    print(f"Done!")
    print(f"  practice-content.js: FACTOR_TREE_DATA ({cases_with_diagrams} diagrams)")
    print(f"  practice.html: COACHING_FRAMEWORKS ({framework_count} frameworks)")


if __name__ == '__main__':
    main()
